### ISSUE TITLE
Sendfile usage documentation typos

### ISSUE THREAD

**Issue by esajic** [jabezwinston/mtp-tools#1]
I've been using your handy DETAILED_USAGE.md instructions to work with mtp-tools in Linux and noticed a couple of typos in the sendfile section. Tried to submit a PR but looks like your repo doesn't allow it so am writing to you here. If you want a PR let me know. Cheers :-)

**Comment by jabezwinston** [comment]
@esajic Sorry ! Haven't checked here for while..
Sure, you are welcome. Please submit the PR by forking my repo.

**Comment by esajic** [comment]
Cheers @jabezwinston I have now made PR #2 for this.

**Comment by jabezwinston** [comment]
PR https://github.com/jabezwinston/mtp-tools/pull/2 merged. Thanks ! :smiley:
